// resources/js/GameComponents/WordBoardComponent.svelte
<script>
    import WordAttemptComponent from "@/GameComponents/WordAttemptComponent.svelte";

    export let wordBoard
</script>

<div>
    {#each {length: wordBoard.maxAttempts} as attempt, index}
        {#if wordBoard.guessedWords[index]}
            <WordAttemptComponent
                wordLength={wordBoard.correctWord.length}
                active={false}
                word={wordBoard.guessedWords[index].guess}
            />
        {:else}
            <WordAttemptComponent
                wordLength={wordBoard.correctWord.length}
                active={wordBoard.guessedWords.length === index}
            />
        {/if}
    {/each}
</div>

// resources/js/GameComponents/WordBoardComponent.vue
<script setup>
import WordAttemptComponent from "./WordAttemptComponent.vue";

const props = defineProps(['maxAttempts', 'wordLength', 'correctWord'])
</script>

<template>
<div>
    <WordAttemptComponent v-for="attemptIndex in maxAttempts" :word-length="5" />
</div>
</template>

<style scoped>

</style>
