// resources/js/GameComponents/WordAttemptComponent.vue
<script setup>
import LetterComponent from "./LetterComponent.vue";

const wordLengthClassMap = {
    3: 'grid-cols-3',
    4: 'grid-cols-4',
    5: 'grid-cols-5',
    6: 'grid-cols-6',
}

defineProps(['wordLength'])
</script>

<template>
    <div class="mx-auto grid" :class="wordLengthClassMap[wordLength]" style="max-width:500px">
        <LetterComponent v-for="wordIndex in wordLength" />
    </div>
</template>

<style scoped>

</style>

// resources/js/GameComponents/WordAttempt.svelte
<script>
    import Letter from "./Letter.svelte";

    const wordLengthClassMap = {
        3: 'grid-cols-3',
        4: 'grid-cols-4',
        5: 'grid-cols-5',
        6: 'grid-cols-6',
    }

    export let wordLength
</script>

<div class={['mx-auto', 'grid', wordLengthClassMap[wordLength]]} style="max-width:500px">
    {#each Array.from({length: wordLength}) as letter, index}
        <Letter />
    {/each}
</div>
